### ISSUE TITLE
LOG IN 버튼을 통해 Redirection 시 간헐적으로 mainmain으로 이동

### ISSUE THREAD

**Issue by charmingjae** [innovationacademy-kr/42checkin_v3-frontend#30]
일정 시간이 지난 후 재 로그인 시 **~.kr/main**이 아닌 **~.kr/mainmain**으로 이동하여 404 페이지로 접근됩니다.

**Comment by 6mn12j** [comment]
이슈 감사합니다. 
기존 주소창의 뒤에 main 만 붙혀서 리다이렉트 시켜서 생긴 문제 같습니다. 해당 부분 수정하고 반영 하겠습니다 ~
